version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      # WebSocket configuration
      - WS_URL=wss://ws-feed.exchange.coinbase.com
      - MONITORING_CRYPTOS=${MONITORING_CRYPTOS:-BTC-USD,ETH-USD}
      - VOLUME_THRESHOLD=${VOLUME_THRESHOLD:-1.5}
      - WINDOW_MINUTES=${WINDOW_MINUTES:-5}
      - EMIT_RAW_TRADES=${EMIT_RAW_TRADES:-false}
    networks:
      - app-network
    restart: always
    # Remove dependency on monitoring-bot since WebSocket is now integrated

  # Optional: Keep trading bot if you still need it
  trading-bot:
    build: ./bots/trading
    env_file:
      - .env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  data:
